import { useState } from 'react';
import { AlertTriangle, ChevronDown, Download, Terminal, Wrench } from 'lucide-react';
import type { PythonArtifact, PythonRun } from '../../types/chat';
import { formatBytes } from '../../services/python/pythonResult';
import { useStoredFile } from './useStoredFile';

/**
 * What a `run_python` call put in front of the user.
 *
 * The default state is deliberately quiet: one line saying code ran, with the
 * charts and tables below it. The code itself is behind a disclosure because
 * it is the *model's* working, not the answer — someone who asked for the
 * average of a column wants the number, and someone debugging wants the
 * source, and only the second should have to look at it.
 *
 * Nothing here is a permission prompt. The user did not have to approve this;
 * the model decided the output was worth showing and it is shown.
 */

interface PythonRunCardProps {
  runs: PythonRun[];
}

function MissingNote({ what }: { what: string }) {
  return (
    <p className="text-[11px] text-white/32">
      {what} is not on this device. Files stay where they were made — ask again to produce it here.
    </p>
  );
}

/**
 * A chart, fetched from the device file store.
 *
 * Its own component because the fetch is a hook, and a hook cannot live inside
 * the branch of `ArtifactView` that needs it.
 */
function ImageArtifact({ artifact }: { artifact: Extract<PythonArtifact, { kind: 'image' }> }) {
  // Messages saved before the file store existed carry the bytes inline.
  const stored = useStoredFile(artifact.dataUrl ? undefined : artifact.fileId);
  const source = artifact.dataUrl ?? (stored.status === 'ready' ? stored.url : null);

  if (!source) {
    if (stored.status === 'loading') {
      return <div className="h-40 w-full max-w-md animate-pulse rounded-xl bg-white/[0.04]" />;
    }
    return <MissingNote what="This chart" />;
  }

  return (
    <figure className="m-0">
      <img
        src={source}
        alt={artifact.caption || 'Chart generated by Python'}
        className="max-w-full rounded-xl bg-[#fff]"
      />
      {artifact.caption && (
        <figcaption className="mt-1.5 text-[11px] text-white/40">{artifact.caption}</figcaption>
      )}
    </figure>
  );
}

function FileArtifact({ artifact }: { artifact: Extract<PythonArtifact, { kind: 'file' }> }) {
  const stored = useStoredFile(artifact.dataUrl ? undefined : artifact.fileId);
  const href = artifact.dataUrl ?? (stored.status === 'ready' ? stored.url : null);

  if (!href) {
    if (stored.status === 'loading') {
      return <div className="h-12 w-64 animate-pulse rounded-xl bg-white/[0.04]" />;
    }
    return <MissingNote what={`${artifact.name} (${formatBytes(artifact.size)})`} />;
  }

  return (
    <a
      href={href}
      download={artifact.name}
      className="group inline-flex items-center gap-3 rounded-xl border border-white/10 bg-white/[0.04] px-4 py-2.5 transition hover:border-white/20 hover:bg-white/[0.07]"
    >
      <Download className="h-4 w-4 shrink-0 text-white/45 transition group-hover:text-white/75" />
      <span className="min-w-0">
        <span className="block truncate text-sm text-white/85">{artifact.name}</span>
        <span className="block text-[11px] text-white/35">{formatBytes(artifact.size)}</span>
      </span>
    </a>
  );
}

function ArtifactView({ artifact }: { artifact: PythonArtifact }) {
  if (artifact.kind === 'image') return <ImageArtifact artifact={artifact} />;

  if (artifact.kind === 'table') {
    const hiddenRows = artifact.totalRows - artifact.rows.length;
    const hiddenColumns = artifact.totalColumns - artifact.columns.length;
    return (
      <div>
        {artifact.caption && <p className="mb-1.5 text-[11px] text-white/40">{artifact.caption}</p>}
        {/* The table scrolls inside its own box: a wide DataFrame must not
            make the whole conversation scroll sideways. */}
        <div className="max-h-80 overflow-auto rounded-xl border border-white/8">
          <table className="w-full border-collapse text-left text-xs">
            <thead className="sticky top-0 bg-white/[0.06] backdrop-blur">
              <tr>
                {artifact.index && <th className="px-3 py-2 font-medium text-white/35" />}
                {artifact.columns.map((column, index) => (
                  <th key={`${column}-${index}`} className="whitespace-nowrap px-3 py-2 font-medium text-white/70">
                    {column}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {artifact.rows.map((row, rowIndex) => (
                <tr key={rowIndex} className="border-t border-white/5">
                  {artifact.index && (
                    <td className="whitespace-nowrap px-3 py-1.5 text-white/32">{artifact.index[rowIndex]}</td>
                  )}
                  {row.map((cell, cellIndex) => (
                    <td key={cellIndex} className="whitespace-nowrap px-3 py-1.5 text-white/60">{cell}</td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        {(hiddenRows > 0 || hiddenColumns > 0) && (
          <p className="mt-1.5 text-[11px] text-white/32">
            Showing {artifact.rows.length} of {artifact.totalRows} rows
            {hiddenColumns > 0 ? ` and ${artifact.columns.length} of ${artifact.totalColumns} columns` : ''}.
          </p>
        )}
      </div>
    );
  }

  if (artifact.kind === 'text') {
    return (
      <div>
        {artifact.caption && <p className="mb-1.5 text-[11px] text-white/40">{artifact.caption}</p>}
        <pre className="max-h-60 overflow-auto whitespace-pre-wrap break-words rounded-xl bg-black/25 p-3 text-xs leading-relaxed text-white/65">
          {artifact.text}
        </pre>
      </div>
    );
  }

  return <FileArtifact artifact={artifact} />;
}

function RunView({ run }: { run: PythonRun }) {
  const [showCode, setShowCode] = useState(false);
  const seconds = (run.durationMs / 1000).toFixed(1);

  return (
    <div className="overflow-hidden rounded-2xl border border-white/10 bg-white/[0.03]">
      <button
        type="button"
        onClick={() => setShowCode(current => !current)}
        aria-expanded={showCode}
        className="flex w-full items-center gap-2.5 px-4 py-2.5 text-left transition hover:bg-white/[0.03]"
      >
        {run.tool
          ? <Wrench className="h-3.5 w-3.5 shrink-0 text-white/40" />
          : <Terminal className="h-3.5 w-3.5 shrink-0 text-white/40" />}
        <span className="text-xs text-white/60">
          {run.tool
            ? (run.ok ? `Used ${run.tool.title}` : `${run.tool.title} failed`)
            : (run.ok ? 'Ran Python' : 'Python failed')}
          <span className="text-white/30"> · {seconds}s</span>
          {/* A tool from the registry is someone else's code running here;
              the row says so rather than presenting it as the assistant's own. */}
          {run.tool?.shared && <span className="text-white/30"> · shared tool</span>}
        </span>
        <ChevronDown
          className={`ml-auto h-3.5 w-3.5 shrink-0 text-white/30 transition-transform ${showCode ? 'rotate-180' : ''}`}
        />
      </button>

      {showCode && (
        <div className="border-t border-white/8 px-4 py-3">
          {run.tool && (
            <p className="mb-2 break-all font-mono text-[11px] text-white/45">
              {run.tool.name}({run.tool.args})
            </p>
          )}
          <pre className="max-h-72 overflow-auto whitespace-pre-wrap break-words rounded-xl bg-black/30 p-3 text-xs leading-relaxed text-white/60">
            {run.code}
          </pre>
          {run.stdout && (
            <>
              <p className="mb-1.5 mt-3 text-[10px] uppercase tracking-[0.18em] text-white/28">Output</p>
              <pre className="max-h-48 overflow-auto whitespace-pre-wrap break-words rounded-xl bg-black/30 p-3 text-xs leading-relaxed text-white/55">
                {run.stdout}
              </pre>
            </>
          )}
        </div>
      )}

      {/* A run with nothing to show is what the collapsed row looks like when
          Python only printed — and to the user that reads as "nothing
          happened". Reported from real use, on a turn where the model computed
          an answer correctly and showed a card with no contents. */}
      {run.ok && run.artifacts.length === 0 && run.stdout && !showCode && (
        <pre className="overflow-x-auto border-t border-white/8 px-4 py-2.5 text-xs leading-relaxed text-white/45">
          {run.stdout.trim().split('\n').slice(0, 3).join('\n')}
        </pre>
      )}

      {!run.ok && run.error && (
        <p className="flex items-start gap-2 border-t border-white/8 px-4 py-3 text-xs leading-relaxed text-rose-200/70">
          <AlertTriangle className="mt-0.5 h-3.5 w-3.5 shrink-0" />
          <span className="min-w-0 break-words">{run.error.split('\n').slice(-3).join('\n')}</span>
        </p>
      )}

      {run.artifacts.length > 0 && (
        <div className="flex flex-col gap-3 border-t border-white/8 px-4 py-3">
          {run.artifacts.map((artifact, index) => (
            <ArtifactView key={index} artifact={artifact} />
          ))}
        </div>
      )}
    </div>
  );
}

export function PythonRunCard({ runs }: PythonRunCardProps) {
  if (runs.length === 0) return null;
  return (
    <div className="mt-3 flex max-w-2xl flex-col gap-2">
      {runs.map(run => <RunView key={run.id} run={run} />)}
    </div>
  );
}
