#!/usr/bin/env python3
"""Regenerate src/stylesheet/light-palette.css from Tailwind's theme.css.

Every hue ramp is mirrored (50↔950, 100↔900 … 500 stays) under
:root[data-theme="light"], so dark-authored utility classes keep their
meaning on paper. Run after a Tailwind upgrade that changes the palette.
"""
import re, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
src = (root / 'node_modules/tailwindcss/theme.css').read_text()
vals = dict(re.findall(r'--color-([a-z]+-\d+):\s*([^;]+);', src))
hues = ['red','orange','amber','yellow','lime','green','emerald','teal','cyan','sky','blue','indigo','violet','purple','fuchsia','pink','rose']
steps = [50,100,200,300,400,500,600,700,800,900,950]

# Paper is eight times brighter than black, so a hue at full Tailwind chroma
# reads as a saturated sticker on it. Pull every mirrored chroma back a fifth:
# still unmistakably the brand purple / PRO cyan / Girlie pink, no longer loud.
CHROMA = 0.8

def mute(v: str) -> str:
    m = re.fullmatch(r'oklch\(([\d.]+)% ([\d.]+) ([\d.]+)\)', v)
    if not m:
        return v
    l, c, h = m.groups()
    return f'oklch({l}% {float(c) * CHROMA:.3f} {h})'

out = ["""/* ════════════════════════════════════════════════════════════
   Light mode — generated palette inversion
   ─────────────────────────────────────────────────────────────
   GENERATED by scripts/generate-light-palette.py from Tailwind's own
   theme.css. Do not hand-edit the hue blocks; edit the script and rerun.

   Every hue's lightness ramp is mirrored (50↔950, 100↔900 … 500 stays)
   and its chroma pulled back to 80%, so a class written for the dark UI keeps its *meaning* in light:
   `text-purple-400` (a light accent on black) becomes purple-600 (a
   deep accent on paper), `bg-purple-600 text-white` becomes a soft
   purple-400 fill with ink text. The whole app was authored dark-first
   with hundreds of hard-coded shades; mirroring is what lets one CSS
   block re-theme it instead of an audit of every className.
   ════════════════════════════════════════════════════════════ */
:root[data-theme="light"] {"""]
for h in hues:
    out.append(f"  /* {h} */")
    for s in steps:
        v = vals.get(f'{h}-{1000 - s}')
        if v:
            out.append(f"  --color-{h}-{s}: {mute(v)};")
out.append("}")
(root / 'src/stylesheet/light-palette.css').write_text("\n".join(out) + "\n")
